# Generated by Django 5.2.14 on 2026-06-10 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del prospecto', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('language', models.CharField(choices=[('es', 'Español'), ('en', 'Inglés')], default='es', max_length=5)),
                ('location', models.CharField(blank=True, help_text='Ciudad / Estado', max_length=200)),
                ('source', models.CharField(choices=[('website', 'Sitio Web'), ('meta_ads', 'Meta Ads'), ('google_ads', 'Google Ads'), ('organico', 'Búsqueda Orgánica'), ('redes_sociales', 'Redes Sociales'), ('golden_tickets', 'Golden Tickets (Referido)'), ('consultation_day', 'Consultation Day'), ('podcast', 'Podcast'), ('evento', 'Evento'), ('otro', 'Otro')], default='website', max_length=30)),
                ('campaign', models.CharField(blank=True, help_text='Campaña o anuncio de origen', max_length=200)),
                ('practice_area', models.CharField(choices=[('vawa', 'VAWA'), ('visa_u', 'Visa U'), ('visa_t', 'Visa T'), ('sijs', 'SIJS'), ('ajuste_estatus', 'Ajuste de Estatus'), ('reunion_familiar', 'Reunificación Familiar'), ('defensa_deportacion', 'Defensa de Deportación'), ('naturalizacion', 'Naturalización'), ('proceso_consular', 'Proceso Consular'), ('general', 'General / Inmigración')], default='general', max_length=50)),
                ('stage', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('calificado', 'Calificado'), ('consulta', 'Consulta agendada'), ('contrato', 'Contrato enviado'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado del caso (USD)', max_digits=10, null=True)),
                ('lost_reason', models.CharField(blank=True, help_text='Motivo si se perdió', max_length=300)),
                ('next_followup', models.DateField(blank=True, help_text='Próximo seguimiento', null=True)),
                ('last_contact_at', models.DateTimeField(blank=True, null=True)),
                ('won_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Responsable del seguimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('nota', 'Nota'), ('llamada', 'Llamada'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('reunion', 'Reunión'), ('etapa', 'Cambio de etapa')], default='nota', max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_activities', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='ventas.lead')),
            ],
            options={
                'verbose_name': 'Actividad de Lead',
                'verbose_name_plural': 'Actividades de Lead',
                'ordering': ['-created_at'],
            },
        ),
    ]
