# Generated by Django 5.2.14 on 2026-06-13 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('seguimiento', 'Seguimiento'), ('llamada', 'Llamada'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='seguimiento', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, help_text='Vencimiento del recordatorio', null=True)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Responsable de la tarea', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_tasks_created', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ventas.lead')),
            ],
            options={
                'verbose_name': 'Tarea de Lead',
                'verbose_name_plural': 'Tareas de Lead',
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
    ]
