# Generated by Django 6.0.5 on 2026-05-10 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetricDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('acquisition', 'Adquisición'), ('engagement', 'Engagement'), ('conversion', 'Conversión'), ('brand', 'Marca')], max_length=50)),
                ('source', models.CharField(choices=[('hubspot', 'HubSpot'), ('google_analytics', 'GA4'), ('meta', 'Meta'), ('google_ads', 'Google Ads'), ('manual', 'Manual')], default='manual', max_length=50)),
                ('unit', models.CharField(choices=[('count', 'Conteo'), ('currency', 'Moneda'), ('percentage', 'Porcentaje'), ('time', 'Tiempo')], default='count', max_length=20)),
                ('target_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('period_type', models.CharField(choices=[('daily', 'Diario'), ('weekly', 'Semanal'), ('monthly', 'Mensual')], default='monthly', max_length=20)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='metrics.metricdefinition')),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['metric', 'period_start'], name='metrics_met_metric__a6d303_idx')],
                'unique_together': {('metric', 'period_start', 'period_type')},
            },
        ),
    ]
