# Generated by Django 5.2.14 on 2026-06-13 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('lead_assigned', 'Lead asignado'), ('task_assigned', 'Tarea asignada'), ('task_due', 'Tarea por vencer'), ('followup_overdue', 'Seguimiento vencido'), ('kpi_alert', 'Alerta de KPI'), ('system', 'Sistema')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Ruta interna, ej. /ventas/leads/12', max_length=300)),
                ('read', models.BooleanField(default=False)),
                ('dedup_key', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read'], name='notificatio_recipie_6e3964_idx')],
            },
        ),
    ]
