# Generated by Django 5.2.14 on 2026-06-09 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título del artículo', max_length=300)),
                ('keyword', models.CharField(blank=True, help_text='Keyword SEO principal', max_length=200)),
                ('practice_area', models.CharField(choices=[('vawa', 'VAWA'), ('visa_u', 'Visa U'), ('visa_t', 'Visa T'), ('sijs', 'SIJS'), ('ajuste_estatus', 'Ajuste de Estatus'), ('reunion_familiar', 'Reunificación Familiar'), ('defensa_deportacion', 'Defensa de Deportación'), ('naturalizacion', 'Naturalización'), ('proceso_consular', 'Proceso Consular'), ('general', 'General / Inmigración')], default='general', max_length=50)),
                ('stage', models.CharField(choices=[('idea', 'Idea'), ('redaccion', 'Redacción'), ('revision', 'Revisión'), ('aprobado', 'Aprobado'), ('publicado', 'Publicado')], default='idea', max_length=20)),
                ('priority', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10)),
                ('due_date', models.DateField(blank=True, help_text='Fecha límite', null=True)),
                ('word_count_target', models.PositiveIntegerField(default=800, help_text='Palabras objetivo')),
                ('brief', models.TextField(blank=True, help_text='Brief / ángulo / puntos clave')),
                ('notes', models.TextField(blank=True, help_text='Notas internas del equipo')),
                ('webflow_url', models.URLField(blank=True, help_text='URL en Webflow una vez publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Redactor asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_assignments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Editor/revisor asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post de Blog',
                'verbose_name_plural': 'Posts de Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
