# Generated by Django 5.2.14 on 2026-05-27 02:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('category', models.CharField(choices=[('direct', 'Competidor Directo'), ('indirect', 'Competidor Indirecto')], default='direct', max_length=20)),
                ('practice_areas', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('meta', 'Meta (Facebook/Instagram)'), ('google', 'Google Ads'), ('youtube', 'YouTube'), ('tiktok', 'TikTok')], max_length=20)),
                ('creative_url', models.URLField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
                ('cta', models.CharField(blank=True, max_length=200)),
                ('differentiator', models.TextField(blank=True)),
                ('observed_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ad_observations', to=settings.AUTH_USER_MODEL)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_observations', to='competitors.competitor')),
            ],
            options={
                'ordering': ['-observed_date'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('threat', 'Amenaza'), ('opportunity', 'Oportunidad'), ('observation', 'Observación')], max_length=20)),
                ('impact', models.CharField(choices=[('high', 'Alto'), ('medium', 'Medio'), ('low', 'Bajo')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='competitors.competitor')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompetitorScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('seo', 'SEO'), ('social_media', 'Redes Sociales'), ('advertising', 'Publicidad'), ('web_presence', 'Presencia Web'), ('content', 'Contenido'), ('reviews', 'Reseñas')], max_length=50)),
                ('score', models.DecimalField(decimal_places=1, max_digits=4)),
                ('raw_value', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('similarweb', 'SimilarWeb'), ('api', 'API')], default='manual', max_length=20)),
                ('period', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitors.competitor')),
            ],
            options={
                'ordering': ['-period'],
                'unique_together': {('competitor', 'dimension', 'period')},
            },
        ),
    ]
