# Generated by Django 5.2.14 on 2026-05-28 13:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del avatar, ej: María - La Madre Inmigrante', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción breve del perfil')),
                ('emoji', models.CharField(default='👤', help_text='Emoji representativo', max_length=10)),
                ('quote', models.CharField(blank=True, help_text='Frase que representa al avatar', max_length=500)),
                ('color', models.CharField(default='#0C2054', help_text='Color de acento para el canvas', max_length=7)),
                ('age_range', models.CharField(blank=True, max_length=50)),
                ('location', models.CharField(blank=True, help_text='Ciudad/estado donde vive en EE.UU.', max_length=200)),
                ('origin_country', models.CharField(blank=True, max_length=100)),
                ('family_situation', models.CharField(blank=True, max_length=300)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('immigration_status', models.CharField(blank=True, max_length=200)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('income_range', models.CharField(blank=True, max_length=100)),
                ('goals', models.JSONField(blank=True, default=list, help_text='Metas a corto y largo plazo')),
                ('pain_points', models.JSONField(blank=True, default=list, help_text='Dolores, miedos y frustraciones')),
                ('values', models.JSONField(blank=True, default=list, help_text='Valores que le importan')),
                ('dreams', models.JSONField(blank=True, default=list, help_text='Sueños y aspiraciones')),
                ('interests', models.JSONField(blank=True, default=list, help_text='Intereses y hobbies')),
                ('favorite_brands', models.JSONField(blank=True, default=list, help_text='Marcas y medios que consume')),
                ('media_channels', models.JSONField(blank=True, default=list, help_text='Canales de información que usa')),
                ('objections', models.JSONField(blank=True, default=list, help_text='Por qué podría no contratarnos')),
                ('triggers', models.JSONField(blank=True, default=list, help_text='Qué lo motiva a tomar acción')),
                ('is_primary', models.BooleanField(default=False, help_text='Avatar principal del equipo')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
