# Generated by Django 6.0.5 on 2026-05-10 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('sop', 'SOP'), ('manual', 'Manual'), ('jd', 'Job Description'), ('template', 'Template'), ('policy', 'Política'), ('brand', 'Marca')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('pptx', 'PowerPoint'), ('html', 'HTML'), ('md', 'Markdown')], max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('draft', 'Borrador'), ('archived', 'Archivado')], default='active', max_length=20)),
                ('visibility', models.CharField(choices=[('team', 'Equipo'), ('leadership', 'Liderazgo'), ('all', 'Todos')], default='team', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='documents.tag')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
