# Generated by Django 6.0.5 on 2026-05-10 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.AddField(
            model_name='document',
            name='content_type',
            field=models.CharField(blank=True, help_text='MIME type', max_length=100),
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='object_key',
            field=models.CharField(blank=True, help_text='Clave en R2/S3', max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('sop', 'SOP'), ('manual', 'Manual'), ('jd', 'Job Description'), ('template', 'Template'), ('policy', 'Política'), ('brand', 'Marca')], default='sop', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.PositiveBigIntegerField(default=0, help_text='Tamaño en bytes'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('pptx', 'PowerPoint'), ('xlsx', 'Excel'), ('html', 'HTML'), ('md', 'Markdown'), ('png', 'PNG'), ('jpg', 'JPEG'), ('mp4', 'Video'), ('other', 'Otro')], default='pdf', max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
