# Generated by Django 5.2.14 on 2026-05-31 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Lunes de inicio de la semana')),
                ('tema', models.CharField(choices=[('vawa', 'VAWA'), ('visa_t', 'Visa T'), ('visa_u', 'Visa U'), ('visa_t_laboral', 'Visa T – Laboral'), ('visa_t_trafico', 'Visa T – Tráfico'), ('sijs', 'SIJS'), ('ajuste_estatus', 'Ajuste de Estatus'), ('proceso_consular', 'Proceso Consular')], max_length=50)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('lista', 'Lista para revisar'), ('publicada', 'Publicada')], default='borrador', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
            },
        ),
        migrations.CreateModel(
            name='GridPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(help_text='0=Lunes, 6=Domingo')),
                ('slot', models.CharField(choices=[('carousel', 'Carrusel / Post Estático'), ('foto', 'Foto Abogada/Cliente'), ('reel', 'Reel')], max_length=20)),
                ('format', models.CharField(choices=[('carousel', 'Carrusel'), ('static', 'Post Estático'), ('foto', 'Foto'), ('reel', 'Reel')], max_length=20)),
                ('headline', models.TextField(blank=True, help_text='Texto para la imagen (lo que diseña Sara)')),
                ('slide_titles', models.JSONField(blank=True, default=list, help_text='Títulos de cada slide del carrusel')),
                ('copy', models.TextField(blank=True, help_text='Cuerpo del caption sin hook/CTA/disclaimer/hashtags')),
                ('cta', models.TextField(blank=True)),
                ('hashtags', models.TextField(blank=True)),
                ('caption', models.TextField(blank=True, help_text='Caption completo listo para publicar')),
                ('photo_suggestion', models.TextField(blank=True, help_text='Descripción de qué foto buscar en el archivo')),
                ('video_title', models.TextField(blank=True, help_text='Texto corto que aparece en pantalla al inicio')),
                ('script_points', models.JSONField(blank=True, default=list, help_text='Puntos clave del guión para Gloriana')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='grillas.contentgrid')),
            ],
            options={
                'ordering': ['day_of_week', 'slot'],
                'unique_together': {('grid', 'day_of_week', 'slot')},
            },
        ),
    ]
