# Generated by Django 6.0.5 on 2026-05-10 17:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.userprofile',),
        ),
    ]
