# Generated by Django 6.0.5 on 2026-05-11 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('content', 'Contenido'), ('meeting', 'Reunión'), ('deadline', 'Entrega'), ('campaign', 'Campaña'), ('event', 'Evento')], default='content', max_length=20)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('channel', models.CharField(blank=True, choices=[('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('podcast', 'Podcast'), ('web', 'Web'), ('all', 'Todos')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Programado'), ('published', 'Publicado'), ('draft', 'Borrador'), ('cancelled', 'Cancelado')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
